<head>
	<meta content="text/html; charset=utf-8" http-equiv="content-type" />
	<link rel="shortcut icon" href="favicon.ico" />
	<link href="styles/style.css" rel="stylesheet" type="text/css" />
	<?php echo PageGenerator::getAddedStyles()?>
	<title><?php echo PageGenerator::getPageTitle(true) ?></title>
</head>



<body>
	<div class="bodyInner">
		<div class="container">
			<div class="containerInner">
				<div class="banner">



<html>

<style type="text/css"> 
.logo
{

	-webkit-animation-name: scaler;
	-webkit-animation-duration: 1s;

/*
animation:scaler 1s;
-moz-animation:scaler 1s;
*/
}
	

@-webkit-keyframes scaler
{
from { -webkit-transform: scale(0.50); }
to { -webkit-transform: scale(1.0); }
}

/*
@keyframes scaler
{
from {scale(1.0)}
to {scale(1.0)}
}

@-moz-keyframes scaler 
{
from {scale(1.0)}
to {scale(1.0)}
}
*/


</style>

<div style="position:relative; top:-124; left:-2">
<table width="700" height="215" border="0" bgcolor="transparent">
	<tr>
		<td width="700" height="170">
			<div style="position:relative; top:113; z-index:3;"><img src="header_j_background.png" width="700" height="170" /></div>
		
			<div style="position:relative; top:0; left: 30px; text-shadow: #6374AB 3px 3px 2px; font-family: sans-serif; font-size:60px; z-index:4;" >TECHMUN <b style="color: #FF0033">2015</b></div>
		
			<div style="position:relative; top:-110; left:500px; color:red; font-size:80px; z-index:5"><img class="logo" src="header_j_logo.png" width="166" height="141" /></div>
	
		</td>
	</tr>
	<tr>
		<td width="700" height="10" style="position:relative; top: -101;"><img src="header_j_redbar.png" /></div></td>
	</tr>
</table>
<table width="700" height="35" border="0" style="position:relative; top:-90;" bgcolor="transparent">
    <tr>
        <td width="89" height="35" style="position:relative; top: -17;"><input class="tab" type="image" src="header_j_home.png" onclick="parent.location='index.php'"/></td>
        <td width="124" height="35" style="position:relative; top: -17; left:-4;"><input class="tab" type="image" src="header_j_invitation.png" onclick="parent.location='invitation.php'" /></td>
        <td width="134" height="35" style="position:relative; top: -17; left:-8;"><input class="tab" type="image" src="header_j_committees.png" onclick="parent.location='committees.php'" /></td>
        <td width="209" height="35" style="position:relative; top: -17; left: -12;"><input class="tab" type="image" src="header_j_secretariat.png" onclick="parent.location='secretariat.php'" /></td>
        <td width="145" height="35" style="position:relative; top: -17; left:-16"><input class="tab" type="image" src="header_j_login.png" onclick="parent.location='login.php'" /></td>
   </tr>

</table>
</div>
</html>



</div>
				<div class="content">
					<div class="bodyTop">
					</div>
					<div class="bodyMid">
